"""
refine_qa.py — Two improvements to qa_pairs.json:

1. 'mama_segments': list of {start, end} containing only Mama's voice
   within each answer (strips out interviewer interjections identified
   by '?' or very short acknowledgment segments).

2. 'visitor_question': natural question a user of the app would type,
   generated by Claude from the answer content.

Run once:
    python refine_qa.py
"""

import json
import os
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

QA_PAIRS_FILE  = "./qa_pairs.json"
TRANSCRIPT_FILE = "./transcript.json"
MIN_SEG_CHARS  = 8    # ignore very short filler segments ("嗯", "对", "mm")
MAX_GAP_S      = 1.5  # merge Baba segments separated by < 1.5s


def build_mama_segments(pair: dict, all_segments: list[dict]) -> list[dict]:
    """
    Within the answer window (answer_start → answer_end), collect segments
    that are NOT interviewer interjections (no '?', not too short).
    Merge adjacent segments with small gaps.
    """
    a_start = pair["answer_start"]
    a_end   = pair["answer_end"]

    # Filter to segments inside the answer window
    window = [
        s for s in all_segments
        if s["start"] >= a_start and s["end"] <= a_end + 2
    ]

    # Keep only segments that look like Baba's speech
    baba = []
    for seg in window:
        text = seg["text"].strip()
        if "?" in text:
            continue  # interviewer interjection
        if len(text) < MIN_SEG_CHARS:
            continue  # filler ("嗯", "好", "对")
        baba.append({"start": seg["start"], "end": seg["end"]})

    if not baba:
        # Fallback: use full answer window
        return [{"start": a_start, "end": a_end}]

    # Merge segments with small gaps
    merged = [baba[0].copy()]
    for seg in baba[1:]:
        if seg["start"] - merged[-1]["end"] <= MAX_GAP_S:
            merged[-1]["end"] = seg["end"]
        else:
            merged.append(seg.copy())

    return merged


def generate_visitor_questions(pairs: list[dict]) -> list[str]:
    """Ask Claude to turn each answer into a natural visitor question."""
    client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    items = "\n".join(
        f"[{i}] ANSWER PREVIEW: {p['answer_text'][:200]}"
        for i, p in enumerate(pairs)
    )

    prompt = f"""These are answers from a recorded interview with a Chinese immigrant mother.

For each answer, write the most natural question that a family member or visitor to a memorial
website would type to hear that answer. Write in English. Keep it short (under 10 words),
warm and personal. Think "What was your childhood like?" not "Did you have memories of growing up?"

Return ONLY a JSON array of {len(pairs)} strings, one per answer, in order.

{items}

Return only valid JSON: ["question 0", "question 1", ...]"""

    msg = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}],
    )

    text = msg.content[0].text.strip()
    start = text.find("[")
    end   = text.rfind("]") + 1
    return json.loads(text[start:end])


def main():
    print("Loading files…")
    with open(QA_PAIRS_FILE) as f:
        pairs = json.load(f)
    with open(TRANSCRIPT_FILE) as f:
        all_segments = json.load(f)

    print(f"Building Mama-only segments for {len(pairs)} pairs…")
    for pair in pairs:
        pair["mama_segments"] = build_mama_segments(pair, all_segments)

    print("Generating visitor questions via Claude…")
    visitor_qs = generate_visitor_questions(pairs)

    print("\nVisitor questions:")
    for i, (pair, vq) in enumerate(zip(pairs, visitor_qs)):
        pair["visitor_question"] = vq
        # Count how much interviewer audio we're removing
        baba_dur   = sum(s["end"] - s["start"] for s in pair["mama_segments"])
        total_dur  = pair["answer_end"] - pair["answer_start"]
        removed    = max(0, total_dur - baba_dur)
        print(f"  [{i:02d}] {vq}  ({removed:.0f}s removed)")

    with open(QA_PAIRS_FILE, "w") as f:
        json.dump(pairs, f, ensure_ascii=False, indent=2)

    print(f"\nDone. Saved to {QA_PAIRS_FILE}")


if __name__ == "__main__":
    main()
